info:
  contact: {}
paths:
  /examples/createExample:
    post:
      description: Create Example
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          schema:
            type: object
      tags:
      - Example
  /examples/deleteExample:
    post:
      description: Delete Example
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          schema:
            type: object
      tags:
      - Example
  /examples/getExample:
    get:
      description: Get Example
      parameters:
      - description: the example id
        in: query
        name: exampleId
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            type: object
      tags:
      - Example
  /examples/updateExample:
    post:
      description: Update Example
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          schema:
            type: object
      tags:
      - Example
  /public/ping:
    get:
      description: Ping
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - Public
swagger: "2.0"
