name: Go

on:
  push:
    branches: ["main"]
    paths-ignore: ["README.*", "LICENSE", "assets/**"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.20.x", "1.21.x"]
        include:
          - go: 1.21.x

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          cache: false # managed by golangci-lint

      - name: Download Dependencies
        run: |
          go mod download

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --version

      - name: Lint & Build
        run: |
          make lint
          make build
